name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Name validation
      id: name-validation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Name validation
        setup-command: pip install pytest
        command: pytest graded_ex1_test.py::test_name_validation
        timeout: 3
        max-score: 1
    - name: Email validation
      id: email-validation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Email validation
        setup-command: pip install pytest
        command: pytest graded_ex1_test.py::test_email_validation
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NAME-VALIDATION_RESULTS: "${{steps.name-validation.outputs.result}}"
        EMAIL-VALIDATION_RESULTS: "${{steps.email-validation.outputs.result}}"
      with:
        runners: name-validation,email-validation
